import { useEffect, useState } from "react";
import {
  FaBuilding,
  FaUsers,
  FaMoneyBillWave,
  FaTools,
  FaBriefcase,
  FaFileInvoiceDollar,
  FaShieldAlt,
  FaUserCheck,
} from "react-icons/fa";
import Layout from "../layouts/Layout";

export default function Dashboard() {
  const [userRole, setUserRole] = useState("PM"); // Fallback to 'PM' if not found
  const [userName, setUserName] = useState("User");

  useEffect(() => {
    // Fetch the logged-in user details set during authentication
    const savedUser = localStorage.getItem("user");
    if (savedUser) {
      try {
        const parsed = JSON.parse(savedUser);
        setUserRole(parsed.role || "PM");
        setUserName(parsed.username || "User");
      } catch (e) {
        console.error("Error parsing user data from local storage", e);
      }
    }
  }, []);

  // Define role-specific configuration maps
  const roleConfigs = {
    PM: {
      title: "Property Manager Dashboard",
      stats: [
        { title: "Managed Properties", value: "12", icon: <FaBuilding />, color: "bg-[#0A4429]" },
        { title: "Total Tenants", value: "132", icon: <FaUsers />, color: "bg-[#2E9D47]" },
        { title: "Monthly Collection", value: "KES 1.2M", icon: <FaMoneyBillWave />, color: "bg-[#0A4429]" },
        { title: "Open Tickets", value: "8", icon: <FaTools />, color: "bg-amber-600" },
      ],
      activities: [
        "John Doe paid rent via M-Pesa STK for Unit A-12",
        "New maintenance request submitted for plumbing issues",
        "Fundi assigned to electrical repair task at Block C",
        "Tenant lease signed electronically for Unit B-07",
      ],
    },
    LANDLORD: {
      title: "Landlord Portfolio Insights",
      stats: [
        { title: "Owned Portfolios", value: "3", icon: <FaBuilding />, color: "bg-[#0A4429]" },
        { title: "Occupancy Rate", value: "94%", icon: <FaUsers />, color: "bg-[#2E9D47]" },
        { title: "Net Net Payouts", value: "KES 850K", icon: <FaFileInvoiceDollar />, color: "bg-[#0A4429]" },
        { title: "Pending Expenses", value: "KES 42K", icon: <FaTools />, color: "bg-red-600" },
      ],
      activities: [
        "Monthly disbursement statements generated by PM",
        "KRA rental tax remittance calculations updated",
        "Payout approval initiated for repairs in Unit D-4",
      ],
    },
    PROVIDER: {
      title: "Service Provider Console",
      stats: [
        { title: "Active Work Orders", value: "4", icon: <FaTools />, color: "bg-[#2E9D47]" },
        { title: "Completed Jobs", value: "48", icon: <FaBriefcase />, color: "bg-[#0A4429]" },
        { title: "Pending Invoices", value: "KES 65K", icon: <FaMoneyBillWave />, color: "bg-amber-600" },
        { title: "Profile Rating", value: "4.9/5", icon: <FaUserCheck />, color: "bg-[#0A4429]" },
      ],
      activities: [
        "New plumbing booking received from Property Manager",
        "Job confirmation request sent for system update",
        "Payment disbursed for CCTV installation project",
      ],
    },
    ADMIN: {
      title: "System Administrator Control",
      stats: [
        { title: "Total System Users", value: "1,420", icon: <FaUsers />, color: "bg-[#0A4429]" },
        { title: "Active Pilot Managers", value: "20", icon: <FaBuilding />, color: "bg-[#2E9D47]" },
        { title: "Total Units Tracked", value: "2,150", icon: <FaShieldAlt />, color: "bg-[#0A4429]" },
        { title: "Platform GMV (MTD)", value: "KES 4.8M", icon: <FaMoneyBillWave />, color: "bg-emerald-600" },
      ],
      activities: [
        "New Service Provider profile verified for operations",
        "Daraja API connection log check passed",
        "System audit log exported by administrative staff",
      ],
    },
  };

  // Gracefully fallback to standard PM layout if role string differs
  const currentConfig = roleConfigs[userRole] || roleConfigs["PM"];

  return (
    <Layout>
      <div className="min-h-screen bg-[#F4F1E6]/40 p-4 md:p-8 font-sans">
        {/* Header Greeting Section */}
        <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-3xl font-bold text-[#0A4429] tracking-tight">
              {currentConfig.title}
            </h2>
            <p className="text-sm text-gray-600 mt-1">
              Welcome back, <span className="font-semibold text-[#2E9D47]">{userName}</span>. Here is what is happening across your platform network today.
            </p>
          </div>
          <div className="flex items-center gap-2 bg-[#0A4429]/5 px-4 py-2 rounded-xl border border-[#0A4429]/10 self-start">
            <div className="w-2.5 h-2.5 bg-[#2E9D47] rounded-full animate-pulse"></div>
            <span className="text-xs font-semibold uppercase tracking-wider text-[#0A4429]">
              Role: {userRole}
            </span>
          </div>
        </div>

        {/* Dynamic Metrics Cards Block */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-10">
          {currentConfig.stats.map((item, index) => (
            <div
              key={index}
              className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 transition-all hover:shadow-md"
            >
              <div className="flex justify-between items-center">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">
                    {item.title}
                  </p>
                  <h3 className="text-3xl font-bold mt-2 text-[#0A4429]">
                    {item.value}
                  </h3>
                </div>
                <div className={`${item.color} text-white p-4 rounded-xl text-xl shadow-inner`}>
                  {item.icon}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Modular Content Section Panels */}
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Section Card 1: Context Dependent UI */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            {(userRole === "PM" || userRole === "LANDLORD" || userRole === "ADMIN") ? (
              <>
                <h3 className="text-lg font-bold text-[#0A4429] mb-4">Occupancy Summary</h3>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between text-sm font-medium">
                      <span className="text-gray-600">Occupied Units</span>
                      <span className="text-[#0A4429]">132 (88%)</span>
                    </div>
                    <div className="w-full bg-gray-100 h-2.5 rounded-full mt-2">
                      <div className="bg-[#2E9D47] h-2.5 rounded-full w-[88%]"></div>
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between text-sm font-medium">
                      <span className="text-gray-600">Vacant Units</span>
                      <span className="text-gray-500">18 (12%)</span>
                    </div>
                    <div className="w-full bg-gray-100 h-2.5 rounded-full mt-2">
                      <div className="bg-gray-300 h-2.5 rounded-full w-[12%]"></div>
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <>
                <h3 className="text-lg font-bold text-[#0A4429] mb-4">Performance Insights</h3>
                <div className="space-y-4 text-sm">
                  <div className="flex justify-between border-b pb-2">
                    <span className="text-gray-500">Response Speed</span>
                    <span className="font-semibold text-green-600">Excellent (&lt;2 hrs)</span>
                  </div>
                  <div className="flex justify-between border-b pb-2">
                    <span className="text-gray-500">Profile Visibility</span>
                    <span className="font-semibold text-[#0A4429]">Top 10% in Nairobi</span>
                  </div>
                </div>
              </>
            )}
          </div>

          {/* Section Card 2: Operations Tracker */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <h3 className="text-lg font-bold text-[#0A4429] mb-4">
              {userRole === "PROVIDER" ? "Job Request Funnel" : "Maintenance Health"}
            </h3>
            <div className="space-y-3 text-sm font-medium">
              <div className="flex justify-between items-center p-2 rounded-lg bg-red-50 text-red-700">
                <span>{userRole === "PROVIDER" ? "New Requests" : "Pending Action"}</span>
                <span className="font-bold text-base">8</span>
              </div>
              <div className="flex justify-between items-center p-2 rounded-lg bg-amber-50 text-amber-700">
                <span>In Progress</span>
                <span className="font-bold text-base">5</span>
              </div>
              <div className="flex justify-between items-center p-2 rounded-lg bg-green-50 text-green-700">
                <span>Resolved & Settled</span>
                <span className="font-bold text-base">24</span>
              </div>
            </div>
          </div>

          {/* Section Card 3: Marketplace Overview */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <h3 className="text-lg font-bold text-[#0A4429] mb-4">
              {userRole === "PROVIDER" ? "Verified Categories" : "Marketplace Directory"}
            </h3>
            <div className="space-y-2.5 text-sm">
              {[
                { title: "Electricians", value: "20 Active" },
                { title: "Plumbers", value: "15 Active" },
                { title: "CCTV/Solar Techs", value: "10 Active" },
                { title: "Legal Consultants", value: "4 Certified" },
              ].map((worker, i) => (
                <div key={i} className="flex justify-between items-center text-gray-600">
                  <span>{worker.title}</span>
                  <span className="bg-gray-100 text-[#0A4429] font-medium text-xs px-2.5 py-1 rounded-full">
                    {worker.value}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Dynamic Activity Feed Container */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mt-8">
          <h3 className="text-lg font-bold text-[#0A4429] mb-4">
            Recent Audit Logs &amp; Events
          </h3>
          <div className="space-y-1">
            {currentConfig.activities.map((activity, index) => (
              <div
                key={index}
                className="flex items-center gap-3 py-3 border-b border-gray-50 last:border-none text-sm text-gray-600"
              >
                <div className="w-1.5 h-1.5 bg-[#2E9D47] rounded-full flex-shrink-0"></div>
                <p className="flex-1">{activity}</p>
                <span className="text-xs text-gray-400 font-light">Just now</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Layout>
  );
}